### ISSUE TITLE
alias for nvim :Z -> :cd 

### ISSUE THREAD

**Issue by Sarthak950** [nanotee/zoxide.vim#11]
hey i was using zoxide lately for my terminal navigation and it seems awsom i have alias it to the cd  ( eval "$(zoxide init --cmd cd fish | source)" ) using this i use fish btw 
i installed the zoxide.vim and it uses :Z as it command is there a way to do the same :Z -> :cd

it will be really awsome

**Comment by nanotee** [comment]
The closest thing to a fish alias in vim is probably a command-line abbreviation ([`:h cabbrev`](https://neovim.io/doc/user/map.html#%3Aca))

You could try something along those lines:

```vim
cabbrev <expr> cd getcmdtype() is# ':' && getcmdline() is# 'cd' ? 'Z' : 'cd'
```
