### ISSUE TITLE
Any chance this could work with fzf-lua in Neovim?

### ISSUE THREAD

**Issue by fresh2dev** [nanotee/zoxide.vim#13]
https://github.com/ibhagwan/fzf-lua

**Comment by nanotee** [comment]
It should work with the [`g:zoxide_use_select`](https://github.com/nanotee/zoxide.vim/blob/e50df0b0160363f5dcae60c4f633ade78e59bdc8/doc/zoxide-vim.txt#L72) option:
```lua
require('fzf-lua').register_ui_select()
vim.g.zoxide_use_select = 1
```

**Comment by fresh2dev** [comment]
Fantastic! Very happy with the result. This is what I ended up with (using `lazy.nvim`):

```lua
{
  'nanotee/zoxide.vim',
  cmd = { 'Z', 'Zi' },
  keys = {
    { '<leader>fz', ':Zi<CR>', desc = '[F]ZF [Z]oxide CD' },
  },
  init = function()
    vim.g.zoxide_use_select = 1

    -- If no args are given to Neovim,
    -- open `Zi` on launch.
    if vim.fn.argc() == 0 then
      vim.defer_fn(function()
        vim.cmd 'Zi'
      end, 0)
    end
  end,
}
```

Sincere thanks!

**Comment by jmlucjav** [comment]
hi,

If I understand correctly, the above configuration should work bith just zoxide.nvim and fzf-lua right? I am trying to use with Nvim 0.10.3 and I am getting error messages like these:

```
Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim:Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: nvim_exec2()..function zoxide#zi, line 1: Vim(echoerr):The fzf.vim plugin must be installed
stack traceback:
	[C]: in function 'cmd'
	.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <.../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
	[C]: in function 'nvim_exec2'
```

Would be great to have this working with fzf-lua...

thanks!

**Comment by nanotee** [comment]
Just tried this with a minimal config, it should work if `vim.g.zoxide_use_select = 1` is set correctly

**Comment by jmlucjav** [comment]
so sorry! My bad, totally forgot to set that variable...
It works wonderful!
thanks
