### ISSUE TITLE
Error on Windows 11 with git bash as shell

### ISSUE THREAD

**Issue by janpeterd** [nanotee/zoxide.vim#14]
In my windows configuration I use use git bash, which provides `bash.exe`. In neovim I have set `vim.opt.shell = "bash"`. With this configuration the `Z` command doesn't work and gives error: `bash: /s: No such file or directory`. The Zi command works.

OS: windows 11
NVIM v0.10.0

**Comment by nanotee** [comment]
Does setting the `'shellcmdflag'` option to `-c` fix it?

**Comment by janpeterd** [comment]
No fix but a different error: `bash: line 1: zoxide query --exclude C:UsersjanpeCodereposdotarchnvim.confignvim dot:command not found`

The path I was going to was `C:\users\janpe\code\repos\dot\arch\nvim\.config\nvim`

Also with this option set the `Zi` command breaks.

**Comment by janpeterd** [comment]
I found the `shellslash` option and set it to true and now the path has forward slashes. Still an error:
`bash: line 1: zoxide 'query' '--exclude' 'C:/Users/janpe/Code/repos/dot/arch/nvim/.config/nvim' 'dot': No such file or directory` 

I find it weird that it gives an error because the same command in a bash shell returns the path.
`$  zoxide 'query' '--exclude' 'C:/Users/janpe/Code/repos/dot/arch/nvim/.config/nvim' 'dot'`
Output: `C:\Users\janpe\Code\repos\dot`

**Comment by nanotee** [comment]
I got it to work with this configuration :
```lua
vim.o.shell = '"C:/Program Files/Git/bin/bash.exe"'
vim.o.shellcmdflag = '-c'
vim.o.shellxquote = '('
```

**Comment by janpeterd** [comment]
Yes with these options the `Z` command works. Unfortunately now the I cannot run the `Zi` command. The popup shows `error: unrecognized subcommand ''query''`

**Comment by nanotee** [comment]
I got this error when I set `'shellslash'` to `true`, does removing it fix the problem?

**Comment by janpeterd** [comment]
okay now I just get `unknown option: --no-tmux` on the `Zi` command. This is weird I'm not doing anything with tmux...

**Comment by nanotee** [comment]
What's the output of `fzf --version`? I suspect you may have updated the `fzf.vim` script without first updating your `fzf` binary

**Comment by janpeterd** [comment]
fzf version is 0.52.1 (6432f00)

**Comment by janpeterd** [comment]
updating fzf fixed the issue

**Comment by janpeterd** [comment]
Everything works now, thanks!
