### ISSUE TITLE
Zoxide plugin doesn't follow z - command.

### ISSUE THREAD

**Issue by ashishbinu** [nanotee/zoxide.vim#3]
In terminal ,If I do `z folder1` and then do `z folder2` and then to go back to previous folder I can just do `z -`. So `z -` takes me to folder1 .But that is not the case in `zoxide.vim` plugin. When i do `:Z -` it justs searches the folder with - in the folder name.

**Comment by nanotee** [comment]
I forgot to handle that special case, should be fixed now

**Comment by ashishbinu** [comment]
Thanks for this plugin btw. It's very handy to switch between projects with this.
