### ISSUE TITLE
use telescope instead of fzf

### ISSUE THREAD

**Issue by Suya1671** [nanotee/zoxide.vim#5]
I would like to use telescope instead of fzf. Is there any way?

**Comment by nanotee** [comment]
The `g:zoxide_use_select` option lets you use [`vim.ui.select()`](https://neovim.io/doc/user/lua.html#vim.ui.select()) instead of `fzf`. You can install [nvim-telescope/telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim) and put this in your config:
```lua
require('telescope').load_extension('ui-select')
vim.g.zoxide_use_select = true
```

**Comment by Suya1671** [comment]
thanks.
