### ISSUE TITLE
No matching autocommands: User ZoxideDirChanged when no event configured

### ISSUE THREAD

**Issue by bartlibert** [nanotee/zoxide.vim#9]
I have no User ZoxideDirChanged configured in my system, so every time I execute "Z", I get an error:

```
No matching autocommands: User ZoxideDirChanged 
```

This can be fixed by (I think, not a lot of testing done) by prefixing `doautocmd` with `silent`:

https://github.com/nanotee/zoxide.vim/blob/e50df0b0160363f5dcae60c4f633ade78e59bdc8/autoload/zoxide.vim#L21

**Comment by nanotee** [comment]
Thank you, I was not aware Vim behaved that way (Neovim ignores missing autocommands).
